spring:
  application:
    name: attachment-service
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/attachment_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false





